[en]
  title = "Clusternet"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

# [zh]
#   title = "Clusternet"
#   languageName = "中文"
#   weight = 2
#   languagedir = "ltr"
#   contentdir = "content/zh"
